[package]
name = "specs-blit"
version = "0.1.0"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
blit = "0.5.7"
lazy_static = "1.4.0"
specs = "0.15.1"

[dev-dependencies]
image = "0.22.3"
minifb = "0.15.1"
